--create database weather_sensor_db on localhost:5432--

drop table if exists sensor cascade;
drop table if exists measurement;

create table sensor (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique
);

create table measurement (
    id bigint generated by default as identity primary key,
    temperature numeric not null check (temperature >= -100 and temperature <= 100),
    is_raining boolean not null,
    created_at timestamp not null,
    sensor_id bigint not null,
    foreign key (sensor_id) references sensor(id)
);


--initial values--
insert into sensor (name) values 
('sensor a'),
('sensor b'),
('sensor c');

insert into measurement (temperature, is_raining, created_at, sensor_id) values 
(25.5, true, '2023-10-01 10:00:00', 1),
(15.0, false, '2023-10-01 11:00:00', 1),
(30.2, true, '2023-10-01 12:00:00', 2),
(20.0, false, '2023-10-01 13:00:00', 2),
(22.5, true, '2023-10-01 14:00:00', 3),
(18.8, false, '2023-10-01 15:00:00', 3);
